# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywkZy40XKwRJkLOu2ibmrUOdDeLsFenV
"""

!pip install huggingface_hub

from huggingface_hub import notebook_login

notebook_login()

!pip install langchain_huggingface

# Install dependencies (run only once)
!pip install -q langchain langchain-huggingface huggingface_hub

from huggingface_hub import notebook_login
from langchain_huggingface import HuggingFaceEndpoint

# Login with your Hugging Face API token
notebook_login()

# Use a model that is hosted and accessible
llm = HuggingFaceEndpoint(
    repo_id="HuggingFaceH4/zephyr-7b-beta",
    task="text-generation",
    max_new_tokens=100,
    temperature=0.7
)

# Test the model
response = llm.invoke("What is the capital of Delhi?")
print(response)